name: img
description: Img widget that renders cross-origin images in a browser-safe way.
version: 0.0.1
homepage: https://github.com/flutter/packages/tree/master/packages/img

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
